### ISSUE TITLE
multiple domains support?

### ISSUE THREAD

**Issue by hostalp** [rkosegi/cert-manager-webhook-active24#43]
Does it support multiple domains in some way?
We;ve got several domains managed by active24 and so far we've been able to get only 1 of them to work. If we add more domains then the acme challenge DNS records are created in the 1st one - the one for which this webhook is configured (apiGroup in Helm chart).

Is there any way how to use multiple domains with this webhook?

We can perhaps add the acme challenge CNAME records to the other domains to point to the 1st one, but that looks more like a workaround.

**Comment by hostalp** [comment]
I think i've got it. I had issues with the `groupName` value being wrong in the ClusterIssuer solvers settings. After correcting that (to always match the apiGroup of the cert-manager-webhook-active24 Helm chart) it started to work.
For reference:
```yaml
    solvers:
    - selector:
        dnsNames:
          - domain1.net
          - '*.domain1.net'
          - sub.domain1.net
          - '*.sub.domain1.net'
          - www.sub.domain1.net
      dns01:
        webhook:
          groupName: acme.domain1.net   # apiGroup from cert-manager-webhook-active24 Helm chart
          solverName: active24
          config:
            apiKeySecretRef:
              name: 'active24-apikey'
              key: 'apiKey'
            domain: domain1.net
    - selector:
        dnsNames:
          - domain2.net
          - '*.domain2.net'
          - www.domain2.net
      dns01:
        webhook:
          groupName: acme.domain1.net   # apiGroup from cert-manager-webhook-active24 Helm chart
          solverName: active24
          config:
            apiKeySecretRef:
              name: 'active24-apikey'
              key: 'apiKey'
            domain: domain2.net
```
